apiVersion: v1
kind: Pod
metadata:
  name: gpu-hello-world
  namespace: default
spec:
  runtimeClassName: nvidia
  restartPolicy: Never
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: cuda-container
    image: nvcr.io/nvidia/cuda:13.0.1-base-ubi9
    command: ["nvidia-smi", "-L"]
    resources:
      limits:
        nvidia.com/gpu: 1
